Repository NITIC-Robot-Club/nhk2025b_ros2, pull requests merged in 2025-05, with the labels that each got.

#23 fix(README): pr guide
  README.md
Labels: bug, documentation

#26 feat: nhk2025b_visualize_swerve
  src/visualization/nhk2025b_visualize_swerve/CMakeLists.txt
  src/visualization/nhk2025b_visualize_swerve/include/nhk2025b_visualize_swerve/visualize_swerve.hpp
  src/visualization/nhk2025b_visualize_swerve/package.xml
  src/visualization/nhk2025b_visualize_swerve/src/visualize_swerve.cpp
Labels: additional

#29 fix(nhk2025b_msgs): missing some depend
  src/message/nhk2025b_msgs/package.xml
Labels: bug

#30 feat: add build test actions
  .github/workflows/ros2_ci.yaml
Labels: additional, build-test

#31 feat: map_publisher
  src/behavior/nhk2025b_behavior/CMakeLists.txt
  src/behavior/nhk2025b_behavior/include/nhk2025b_behavior/map_publisher.hpp
  src/behavior/nhk2025b_behavior/package.xml
  src/behavior/nhk2025b_behavior/src/map_publisher.cpp
Labels: additional

#43 fix(actions): compile_commands.json not found
  .clang-format
  .clang-tidy
  .github/workflows/auto_fix_and_build.yaml
  src/common/nhk2025b_map_publisher/include/nhk2025b_map_publisher/map_publisher.hpp
  src/common/nhk2025b_map_publisher/src/map_publisher.cpp
  src/visualization/nhk2025b_visualize_swerve/include/nhk2025b_visualize_swerve/visualize_swerve.hpp
  src/visualization/nhk2025b_visualize_swerve/src/visualize_swerve.cpp
Labels: run_build

#45 feat(actions): fast ci
  .github/workflows/auto_fix_and_build.yaml
Labels: enhancement, run_build

#48 feat(nhk2025b_launch): add rviz launch
  README.md
  clean_build.sh
  colcon_build.sh
  src/launch/nhk2025b_launch/CMakeLists.txt
  src/launch/nhk2025b_launch/launch/container.launch.xml
  src/launch/nhk2025b_launch/launch/launch.launch.xml
  src/launch/nhk2025b_launch/launch/rviz2.launch.xml
  src/launch/nhk2025b_launch/rviz/nhk2025b.rviz
Labels: enhancement

#46 feat: nhk2025b_ekf_localizer
  src/localization/nhk2025b_ekf_localizer/CMakeLists.txt
  src/localization/nhk2025b_ekf_localizer/include/nhk2025b_ekf_localizer/ekf_localizer.hpp
  src/localization/nhk2025b_ekf_localizer/package.xml
  src/localization/nhk2025b_ekf_localizer/src/ekf_localizer.cpp
Labels: additional, run_build

#50 feat: nhk2025b_canable
  src/common/nhk2025b_canable/CMakeLists.txt
  src/common/nhk2025b_canable/include/nhk2025b_canable/canable.hpp
  src/common/nhk2025b_canable/package.xml
  src/common/nhk2025b_canable/src/canable.cpp
Labels: run_build

#52 feat: nhk2025b_simulation
  src/launch/nhk2025b_launch/rviz/nhk2025b.rviz
  src/simulation/nhk2025b_simulation/CMakeLists.txt
  src/simulation/nhk2025b_simulation/include/nhk2025b_simulation/simulation.hpp
  src/simulation/nhk2025b_simulation/package.xml
  src/simulation/nhk2025b_simulation/src/simulation.cpp
Labels: additional, run_build

#55 fix: topic name
  src/localization/nhk2025b_ekf_localizer/src/ekf_localizer.cpp
  src/visualization/nhk2025b_visualize_swerve/src/visualize_swerve.cpp
Labels: run_build

#58 feat: nhk2025b_swerve_calculator
  src/control/nhk2025b_swerve_calculator/CMakeLists.txt
  src/control/nhk2025b_swerve_calculator/README.md
  src/control/nhk2025b_swerve_calculator/include/nhk2025b_swerve_calculator/swerve_calculator.hpp
  src/control/nhk2025b_swerve_calculator/package.xml
  src/control/nhk2025b_swerve_calculator/src/swerve_calculator.cpp
Labels: run_build

#63 fix: float to double bug
  .gitignore
  .vscode/settings.json
  src/common/nhk2025b_map_publisher/include/nhk2025b_map_publisher/map_publisher.hpp
  src/common/nhk2025b_map_publisher/src/map_publisher.cpp
  src/control/nhk2025b_swerve_calculator/include/nhk2025b_swerve_calculator/swerve_calculator.hpp
  src/control/nhk2025b_swerve_calculator/src/swerve_calculator.cpp
  src/simulation/nhk2025b_simulation/include/nhk2025b_simulation/simulation.hpp
  src/simulation/nhk2025b_simulation/src/simulation.cpp
  src/visualization/nhk2025b_visualize_swerve/include/nhk2025b_visualize_swerve/visualize_swerve.hpp
  src/visualization/nhk2025b_visualize_swerve/src/visualize_swerve.cpp
Labels: bug, run_build

#69 fix: get param func
  src/common/nhk2025b_map_publisher/src/map_publisher.cpp
  src/simulation/nhk2025b_simulation/src/simulation.cpp
  src/visualization/nhk2025b_visualize_swerve/src/visualize_swerve.cpp
Labels: bug

#70 feat: nhk2025b_wheel_odometory
  src/control/nhk2025b_swerve_calculator/src/swerve_calculator.cpp
  src/launch/nhk2025b_launch/launch/container.launch.xml
  src/launch/nhk2025b_launch/launch/simulation.launch.xml
  src/launch/nhk2025b_launch/rviz/nhk2025b.rviz
  src/localization/nhk2025b_wheel_odometory/CMakeLists.txt
  src/localization/nhk2025b_wheel_odometory/include/nhk2025b_wheel_odometory/wheel_odometory.hpp
  src/localization/nhk2025b_wheel_odometory/package.xml
  src/localization/nhk2025b_wheel_odometory/src/wheel_odometory.cpp
  src/simulation/nhk2025b_simulation/src/simulation.cpp
  src/visualization/nhk2025b_visualize_swerve/src/visualize_swerve.cpp
Labels: run_build

#72 fix(actions): no fix and build diff when label
  .github/workflows/auto_fix.yaml
  .github/workflows/auto_fix_and_build.yaml
  .github/workflows/build_differential.yaml
Labels: run_build

#74 add(nhk2025b_simulation): lidar simulation
  src/launch/nhk2025b_launch/launch/simulation.launch.xml
  src/launch/nhk2025b_launch/rviz/nhk2025b.rviz
  src/localization/nhk2025b_wheel_odometory/src/wheel_odometory.cpp
  src/simulation/nhk2025b_simulation/CMakeLists.txt
  src/simulation/nhk2025b_simulation/include/nhk2025b_simulation/lidar_simulation.hpp
  src/simulation/nhk2025b_simulation/package.xml
  src/simulation/nhk2025b_simulation/src/lidar_simulation.cpp
Labels: run_build

#67 feat: nhk2025b_pure_pursuit
  .vscode/extensions.json
  src/control/nhk2025b_pure_pursuit/CMakeLists.txt
  src/control/nhk2025b_pure_pursuit/include/nhk2025b_pure_pursuit/pure_pursuit.hpp
  src/control/nhk2025b_pure_pursuit/package.xml
  src/control/nhk2025b_pure_pursuit/src/pure_pursuit.cpp
  src/launch/nhk2025b_launch/launch/simulation.launch.xml
  src/launch/nhk2025b_launch/rviz/nhk2025b.rviz
  src/simulation/nhk2025b_simulation/src/simulation.cpp
Labels: additional, run_build

#80 feat: nhk2025b_mcl
  .github/workflows/build_differential.yaml
  src/common/nhk2025b_map_publisher/include/nhk2025b_map_publisher/map_publisher.hpp
  src/common/nhk2025b_map_publisher/src/map_publisher.cpp
  src/control/nhk2025b_pure_pursuit/src/pure_pursuit.cpp
  src/launch/nhk2025b_launch/CMakeLists.txt
  src/launch/nhk2025b_launch/launch/default.launch.xml
  src/launch/nhk2025b_launch/launch/launch.launch.xml
  src/launch/nhk2025b_launch/launch/localization.launch.xml
  src/launch/nhk2025b_launch/launch/simulation.launch.xml
  src/launch/nhk2025b_launch/launch/swerve.launch.xml
  src/launch/nhk2025b_launch/launch/tf.launch.xml
  src/launch/nhk2025b_launch/param/global_settings.yaml
  src/launch/nhk2025b_launch/param/localization/mcl.yaml
  src/launch/nhk2025b_launch/rviz/nhk2025b.rviz
  src/localization/nhk2025b_ekf/CMakeLists.txt
  src/localization/nhk2025b_ekf/README.md
  src/localization/nhk2025b_ekf/include/nhk2025b_ekf/ekf.hpp
  src/localization/nhk2025b_ekf/package.xml
  src/localization/nhk2025b_ekf/src/ekf.cpp
  src/localization/nhk2025b_mcl/CMakeLists.txt
  src/localization/nhk2025b_mcl/README.md
  src/localization/nhk2025b_mcl/include/nhk2025b_scan_matcher/mcl.hpp
  src/localization/nhk2025b_mcl/package.xml
  src/localization/nhk2025b_mcl/src/mcl.cpp
  src/localization/nhk2025b_wheel_odometory/src/wheel_odometory.cpp
  src/planning/nhk2025b_path_planner/src/path_planner.cpp
  src/simulation/nhk2025b_simulation/src/simulation.cpp
Labels: additional, run_build

#93 feat(mcl): add robot speed
  .github/workflows/build_differential.yaml
  src/launch/nhk2025b_launch/launch/localization.launch.xml
  src/launch/nhk2025b_launch/launch/simulation.launch.xml
  src/launch/nhk2025b_launch/param/lidar_simulation.yaml
  src/launch/nhk2025b_launch/param/localization/mcl.yaml
  src/launch/nhk2025b_launch/param/mcl.yaml
  src/launch/nhk2025b_launch/rviz/nhk2025b.rviz
  src/localization/nhk2025b_mcl/include/nhk2025b_scan_matcher/mcl.hpp
  src/localization/nhk2025b_mcl/src/mcl.cpp
  src/localization/nhk2025b_wheel_odometry/src/wheel_odometry.cpp
  src/simulation/nhk2025b_simulation/include/nhk2025b_simulation/lidar_simulation.hpp
  src/simulation/nhk2025b_simulation/src/lidar_simulation.cpp
Labels: enhancement

#96 feat(nhk2025b_path_planner): add A* planning
  src/planning/nhk2025b_path_planner/include/nhk2025b_path_planner/path_planner.hpp
  src/planning/nhk2025b_path_planner/src/path_planner.cpp
Labels: run_build_diff

#100 feat (nhk2025b_pure_pursuit): dynamic lookahead pose and consider acceleration
  src/control/nhk2025b_pure_pursuit/include/nhk2025b_pure_pursuit/pure_pursuit.hpp
  src/control/nhk2025b_pure_pursuit/src/pure_pursuit.cpp
  src/launch/nhk2025b_launch/launch/default.launch.xml
  src/launch/nhk2025b_launch/launch/localization.launch.xml
  src/launch/nhk2025b_launch/launch/planning.launch.xml
  src/launch/nhk2025b_launch/launch/simulation.launch.xml
  src/launch/nhk2025b_launch/param/common.yaml
  src/launch/nhk2025b_launch/param/control.yaml
  src/launch/nhk2025b_launch/param/localization.yaml
  src/launch/nhk2025b_launch/param/planning.yaml
  src/launch/nhk2025b_launch/param/simulation.yaml
  src/launch/nhk2025b_launch/rviz/nhk2025b.rviz
  src/planning/nhk2025b_path_planner/src/path_planner.cpp
Labels: enhancement, run_build_diff

#103 fix (vscode): include path
  .vscode/c_cpp_properties.json
Labels: bug

#107 fix(README): add topic io table and function description
  src/behavior/README.md
  src/behavior/nhk2025b_behavior/README.md
  src/common/README.md
  src/common/nhk2025b_canable/README.md
  src/common/nhk2025b_map_publisher/README.md
  src/control/README.md
  src/control/nhk2025b_pure_pursuit/README.md
  src/control/nhk2025b_swerve_calculator/README.md
  src/launch/README.md
  src/launch/nhk2025b_launch/README.md
  src/localization/README.md
  src/localization/nhk2025b_ekf/README.md
  src/localization/nhk2025b_mcl/README.md
  src/localization/nhk2025b_pose_initializer/README.md
  src/localization/nhk2025b_wheel_odometry/README.md
  src/message/README.md
  src/planning/README.md
  src/planning/nhk2025b_path_planner/README.md
  src/simulation/README.md
  src/simulation/nhk2025b_simulation/README.md
  src/visualization/README.md
  src/visualization/nhk2025b_footprint_publisher/README.md
  src/visualization/nhk2025b_visualize_swerve/README.md
Labels: documentation

#110 fix (nhk2025b_pure_pursuit): angle does not follow
  src/control/nhk2025b_pure_pursuit/include/nhk2025b_pure_pursuit/pure_pursuit.hpp
  src/control/nhk2025b_pure_pursuit/src/pure_pursuit.cpp
  src/localization/nhk2025b_mcl/src/mcl.cpp
Labels: run_build_diff
